# Generated by Django 4.2.11 on 2024-07-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyuser",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="is_superuser",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
