# Generated by Django 4.2.11 on 2024-07-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_companyuser_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="mobile",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
